//
//  MovieListModels.swift
//  ListProject
//
//  Created by Ruy de Ascenção Neto on 31/08/20.
//  Copyright (c) 2020 CocoaPods. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieList{
  // MARK: Use cases
  enum ShowList{
    struct Request{
    }
    struct Response{
        var movieList:[MovieListResponse.Movie]
    }
    struct ViewModel{
        struct MovieVM{
            var name:String
            var description:String
        }
        var movieList:[MovieVM]
    }
  }
}
