//
//  MovieListPresenter.swift
//  ListProject
//
//  Created by Ruy de Ascenção Neto on 31/08/20.
//  Copyright (c) 2020 CocoaPods. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListPresentationLogic
{
    func presentMoviesList(movieList:MovieList.ShowList.Response)
}

class MovieListPresenter: MovieListPresentationLogic{
   
    
    weak var viewController: MovieListDisplayLogic?
  
  // MARK: Do something
  
    func presentMoviesList(movieList:MovieList.ShowList.Response){
        var list:[MovieList.ShowList.ViewModel.MovieVM] = []
        for movie in movieList.movieList{
            list.append(MovieList.ShowList.ViewModel.MovieVM(name: movie.title!, description: movie.overview!))
        }
        viewController?.displayList(movieList: MovieList.ShowList.ViewModel(movieList: list))
    }
}
