use_frameworks!
platform :ios, '9.0'

target 'ListProject_Example' do
  pod 'ListProject', :path => '../'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SnapKit', '~> 4.0'

  target 'ListProject_ExampleTests' do
    inherit! :search_paths
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'SnapKit', '~> 4.0'
 end
end
